---
language: node_js

node_js:
  - 8

dist: trusty

cache:
  yarn: true
  directories:
  - node_modules

before_script:
  - yarn install

script:
  - yarn test-with-coverage
  - yarn send-test-coverage
